services:
  remote-mcp-neo4j-cypher-server:
    image: mcp/neo4j-cypher:latest
    ports:
      - "${REMOTE_MCP_NEO4J_PORT:-8095}:8000"
    environment:
      - NEO4J_URI=${REMOTE_NEO4J_URI}
      - NEO4J_URL=${REMOTE_NEO4J_URI}  # For compatibility with the Docker image
      - NEO4J_USERNAME=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-demodemo}
      - NEO4J_DATABASE=neo4j
      - NEO4J_TRANSPORT=sse
      - NEO4J_MCP_SERVER_HOST=0.0.0.0 # must be 0.0.0.0 for sse transport in Docker
      - NEO4J_MCP_SERVER_PORT=8000
    command: ["pip install --upgrade mcp-neo4j-cypher==0.2.4 && mcp-neo4j-cypher --server-host 0.0.0.0 --server-port 8000"]
    entrypoint: ["sh", "-c"]

  remote-graphiti-mcp:
    image: ghcr.io/mkxultra/graphiti-mcp-server-extended:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env.remote
        required: false # Makes the file optional. Default value is 'true'
    environment:
      - NEO4J_URI=${REMOTE_NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-demodemo}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME}
      - PATH=/root/.local/bin:${PATH}
      - SEMAPHORE_LIMIT=${SEMAPHORE_LIMIT:-10}
    ports:
      - "${REMOTE_GRAPHITI_MCP_PORT:-8096}:8000" # Expose the MCP server via HTTP for SSE transport
    command: ["uv", "run", "graphiti_mcp_server.py", "--transport", "sse"]

